# Generated by Django 4.1.5 on 2023-01-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
        ('booking', '0002_alter_booking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_en',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_ru',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_guests_en',
            field=models.CharField(max_length=1, null=True, verbose_name='Number of guests'),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_guests_ru',
            field=models.CharField(max_length=1, null=True, verbose_name='Number of guests'),
        ),
        migrations.AddField(
            model_name='booking',
            name='table_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='table.table', verbose_name='Table'),
        ),
        migrations.AddField(
            model_name='booking',
            name='table_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='table.table', verbose_name='Table'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_en',
            field=models.TimeField(null=True, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_ru',
            field=models.TimeField(null=True, verbose_name='Time'),
        ),
    ]
