# Generated by Django 4.1.5 on 2023-01-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_remove_menu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('img', models.ImageField(upload_to='users/photos/', verbose_name='Photo of restaurant')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restauraunt', to='menu.menu', verbose_name='')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
